name: Mini Blockchain CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up
      run: sudo apt-get update && sudo apt-get install -y libssl-dev build-essential

    - name: Build
      run: |
        make fclean
        make

    - name: Run
      run: |
        ./blockchain
    
    - name: clean
      run: make fclean